# Generated by Django 2.2.7 on 2019-12-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobileno', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
