# Generated by Django 2.2.7 on 2019-12-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
